---
title: "Contact"
toc: true
toc-depth: 3
---

## Contact information

**E-mail (academic):** minku93@korea.ac.kr

**E-mail (general):** kangminku.kr@gmail.com

**Social:**

- LinkedIn: <https://www.linkedin.com/in/kangminku/>
- Facebook: <https://facebook.com/kaangminku>
- Instagram: <https://instagram.com/kangminku.kr/>

📍 Seoul, Korea

Hello, I am open to collaboration with anyone as long as it interests me. Please feel free to contact me anytime via kangminku.kr@gmail.com. I will get back to you within 24 hours. Please feel free to contact me via cell phone messenger if you haven't heard from me. Thank you.

안녕하세요, 저는 관심 주제에 대한 협업을 언제나 희망합니다. 협업을 희망하시는 분은 언제든지 kangminku.kr@gmail.com 로 연락을 부탁드립니다. 가능하면 24시간 내에 답변을 드리도록 하겠습니다, 혹시 연락이 닿지 않으면 휴대폰 메신저를 통하여 연락주셔도 괜찮습니다. 감사합니다.

## Areas of interest

Public Mental Health, Social Epidemiology, Health Inequalities, Suicide Prevention, Community Health, Workplace Health, Occupational Medicine, Social Determinants of Health, Health Systems and Policies, Social Policy, Preventive Medicine, Lifestyle Medicine, Health Workforce, Urban Planning and Health, Healthy Cities, Pandemic Preparedness, Environmental Health, Global Health, Public Policy, Welfare State, Political Sociology, Rational Choice Institutionalism, Macro-Comparative Research, and Human Rights.
